[workspace]
members = [
    "bluejay-core",
    "bluejay-parser",
    "bluejay-printer",
    "bluejay-typegen",
    "bluejay-typegen-macro",
    "bluejay-validator",
    "bluejay-visibility",
]
resolver = "2"
