query MyQuery {
  myField
  myAliasedField: myField
  myNestedField { myField }
  myRequiredField
  myNestedFieldWithFragment: myNestedField { ...MyFragment }
  type: myField
  myEnum
  myDecimals
}

query Player {
  player {
    __typename
    ...on Skater {
      name
      age
      position
      stats { goals }
    }
    ...on Goalie {
      name
      age
      stats { wins }
    }
  }
}

query BuiltinScalars {
  builtinScalars {
    id
    int
    float
    string
    boolean
  }
}

fragment MyFragment on MyInterface {
  myField
}

query MyStrEnum {
  myStrEnum
}

query MyArgs(
  "A required argument"
  $required: String!
  $optional: Int
  $withDefault: Int! = 1
  $list: [MyStrEnum!]
  $input: MyInput
  $decimal: Decimal
  $enum: MyEnum
) {
  myArgs(
    required: $required
    optional: $optional
    withDefault: $withDefault
    list: $list
    input: $input
    decimal: $decimal
    enum: $enum
  )
}
